django_assessment/django_assessment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('dogs/', include('dogs.urls', namespace='dogs')),
    path('admin/', admin.site.urls),
]

django_assessment/dogs/urls.py
from django.urls import path
from dogs import views

app_name = 'dogs'

urlpatterns = [
	path('view-dogs/', views.view_dogs, name='view_dogs'),
	path('profile/<int:dognum>', views.dog_profile, name='dog_profile'),
	path('add-dog/', views.add_dog, name='add_dog'),
]

django_assessment/dogs/models.py
from django.db import models

# Create your models here.

class Dog(models.Model):
	name = models.CharField(max_length=30)
	breed = models.CharField(max_length=30)
	age = models.CharField(max_length=3)
	weight = models.CharField(max_length=30)
	details = models.CharField(max_length=200)

	def __str__(self):
		return self.name

	def get_all(self):
		return [self.name, self.breed, self.age, self.weight, self.details]

django_assessment/dogs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . models import Dog

# Create your views here.

def view_dogs(request):
	dogs = Dog.objects.all
	#return HttpResponse(dogs)
	return render(
		request,
		'view_dogs.html',
		{'dogs': dogs},
	)


def dog_profile(request, dognum):
	dog = Dog.objects.filter(id=dognum)
	return render(
		request,
		'dog_profile.html',
		{'dog': dog},
	)


def add_dog(request):
	if request.method == 'POST':
		dog_instance = Dog.objects.create(
			name = request.POST.get('name'),
			breed = request.POST.get('breed'),
			age = request.POST.get('age'),
			weight = request.POST.get('weight'),
			details = request.POST.get('details'),
		)
		return render(request, 'added_dog.html')

	return render(request, 'add_dogs.html')

django_assessment/templates/add_dogs.html
{% extends "base.html" %}

{% block title %}Add Dogs{% endblock %}

{% block head %}<h3>Add Dogs!</h3>{% endblock %}

{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		Name: <input type="text" name="name"><br><br>
		Breed: <input type="text" name="breed"><br><br>
		Age: <input type="text" name="age"><br><br>
		Weight: <input type="text" name="weight"><br><br>
		Details: <input type="text" name="details"><br><br>
		<input type="submit" value="Add">
	</form>
{% endblock %}

{% block footer %}
	<hr>
	<a href="{% url 'dogs:view_dogs' %}">Back to viewing dogs</a>
{% endblock %}

django_assessment/templates/added_dog.html
{% extends "base.html" %}

{% block title %}Add Dogs{% endblock %}

{% block head %}<h3>Successfully Added Dog!</h3>{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
	<hr>
	<a href="{% url 'dogs:view_dogs' %}">Back to viewing dogs</a>
{% endblock %}

django_assessment/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	{% block head %}{% endblock %}
	{% block content %}{% endblock %}
	{% block footer %}{% endblock %}
</body>
</html>

django_assessment/templates/dog_profile.html
{% extends "base.html" %}

{% block title %}Dog Profile{% endblock %}

{% block head %}{% endblock %}

{% block content %}
	<table>
	{% for list in dog %}
		{% for attribute in list.get_all %}
			<tr><td>{{ attribute }}</td></tr>
		{% endfor %}
	{% endfor %}
	</table>
{% endblock %}

{% block footer %}
	<hr>
	<a href="{% url 'dogs:view_dogs' %}">View dogs</a>
{% endblock %}

django_assessment/templates/view_dogs.html
{% extends "base.html" %}

{% block title %}View Dogs{% endblock %}

{% block head %}<h3>Dogs!</h3>{% endblock %}

{% block content %}
	<table>
	{% for dog in dogs %}
		<td><a href="{% url 'dogs:dog_profile' dognum=dog.id %}">{{ dog.name }}</a></td>
	{% endfor %}
	</table>
{% endblock %}

{% block footer %}
	<hr>
	<a href="{% url 'dogs:add_dog' %}">Add more dogs</a>
{% endblock %}